[ env ]
TERM = "xterm-256color"
startup_mode = "Fullscreen" 

[window]
padding.x = 0
padding.y = 0
decorations = "Buttonless"
# opacity=0.8
blur=true
title="omega"


[font]
normal.family = "Hack Nerd Font "
bold.style="bold"
size = 14

[selection]
save_to_clipboard = true 

[cursor]
blink_interval= 200

[general]
import = [
    "~/.config/alacritty/theme.toml"
]
