
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "Hack Nerd Font"

#regular
size = 14

[general]
import = [
    "~/.config/alacritty/theme.toml"
]
